name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Nix
      uses: cachix/install-nix-action@v6
    - name: Cachix
      uses: cachix/cachix-action@v2
      with:
        attributes: kernel
        name: blitz 
        signingKey: $cachixSecretKey
